### PR TITLE
Build a new string from an escaped string fails

### PR DESCRIPTION
**Pull request by tylerturdenpants**
AST to see things: 
https://astexplorer.net/#/gist/72cfb408b5843c705909e0720854ace9/dd4bf118c3be8ec33222d0edab7df0f217da96dd

### CODE REVIEW

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/glimmerjs/glimmer-vm/pull/835 once it lands.

**Comment by rwjblue** [comment]
@tylerturdenpants - Can you bump @glimmer/syntax to 0.45.2? I think that should make this test pass.

**Comment by tylerturdenpants** [comment]
@rwjblue yup!

**Comment by tylerturdenpants** [comment]
@rwjblue PASS!

**Comment by rwjblue** [comment]
Rebased (to fix yarn.lock conflict).

**Pull request merged**
