### PR TITLE
failing-test: attributes order after modification

### PR DESCRIPTION
**Pull request by lifeart**
issue reproducible for  https://gitlab.com/michal.bryxi/ember-template-lint-plugin-tailwindcss fix logic

image

### CODE REVIEW

**Comment by dcyriller** [comment]
I'm not sure if this should be considered as a bug or as an expected behavior. 🙂

For now, inserted attributes are appended to the attributes / comments / modifiers list of an html element node. I pushed a commit to show how the behavior could be changed. It would be a breaking change.

**Comment by rwjblue** [comment]
We still need to decide if we want to move forward here... 🤔

**Comment by Alonski** [comment]
@rwjblue Can we look into this again?
I am trying to order attributes during a template lint fix and its... not working how I expect :)

**Comment by dcyriller** [comment]
oops 🙈 bad timing sorry - it was during my vacations

I've had a look again today. And I think it is worth changing the current behavior.

Related: we could also allow modifying the attributes order through the ast - wdyt @rwjblue? I opened https://github.com/ember-template-lint/ember-template-recast/pull/353 for discussion purpose.

**Review by dcyriller — APPROVED** [review]

**Comment by Alonski** [comment]
@rwjblue Can we get this merged/reviewed?

**Pull request merged**
