### PR TITLE
Pin colors dependency to avoid CI issues

### PR DESCRIPTION
**Pull request by SergeAstapov**
For background one may follow Marak/colors.js#285

### CODE REVIEW

**Review by MelSumner — APPROVED** [review]
Thank you for doing this.

**Comment by MelSumner** [comment]
Cc @rwjblue @bmish

**Comment by bmish** [comment]
Is this still necessary now that the bad version was removed?

**Comment by SergeAstapov** [comment]
> Is this still necessary now that the bad version was removed?

Seem like we can avoid this change.

**Pull request closed without merging**
