### PR TITLE
Fix the scenario where block params are on a new line

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by rwjblue** [comment]
Don't get me wrong, its definitely a bug and we'll fix it. I'm just surprised its done this way by folks...

**Comment by NullVoxPopuli** [comment]
I think the closest thing I've seen is:
```hbs
<SomeComponent 
  @arg={{property}} 
  @foo='bar'
  @baz='idk'
  as |foo|
>
</SomeComponent>
```
where `as` is on the same line as the pipes. :man_shrugging: 

there _isn't_ a bug when as is on the same line as the pipes, which is good

**Comment by rwjblue** [comment]
> where as is on the same line as the pipes. 🤷‍♂

Ya, thats what I've seen a bunch as well. Sometimes its dedented to align with the indent of the `<Foo` and other times its still indented, but generally speaking the `as |` relationship is the same (`as` one space then `|`).

Either way though, I'll dig into this a bit and see how to fix.

**Comment by dcyriller** [comment]
Thanks a lot for the report!

**Pull request merged**
