### PR TITLE
test(#586): can reuse previous concat parts

### PR DESCRIPTION
**Pull request by MichalBryxi**
- Test proving that when you reuse parts from previous concat statement in new concat statement you will get "Maximum callstack size exceeded"

Running this:

```
❯ yarn jest src/parse-result.test.ts -t 'can reuse previous concat parts'
```

Gives me:

```
  ● ember-template-recast › ElementNode › can reuse previous concat parts

    RangeError: Maximum call stack size exceeded

      19 |   // TODO: write a test for this case
      20 |   if (parseResult === undefined) {
    > 21 |     return glimmerPrint(ast, {
         |                         ^
      22 |       entityEncoding: 'raw',
      23 |       override: (ast) => {
      24 |         if (NODE_INFO.has(ast)) {

      at print (src/index.ts:21:25)
      at Object.override (src/index.ts:25:18)
      at Printer.print (node_modules/@glimmer/syntax/packages/@glimmer/syntax/lib/generation/printer.ts:539:20)
      at Object.build (node_modules/@glimmer/syntax/packages/@glimmer/syntax/lib/generation/print.ts:13:10)
      at print (src/index.ts:21:12)
      at Object.override (src/index.ts:25:18)
      at Printer.print (node_modules/@glimmer/syntax/packages/@glimmer/syntax/lib/generation/printer.ts:539:20)
      at Object.build (node_modules/@glimmer/syntax/packages/@glimmer/syntax/lib/generation/print.ts:13:10)
      at print (src/index.ts:21:12)
      at Object.override (src/index.ts:25:18)
```

### CODE REVIEW

**Comment by MichalBryxi** [comment]
I found even simpler reproduction. Seems like one just needs to pass into `print()` partial output of `parse()`. Anything but the whole output from `parse` will trigger this error.

Not sure if the other test is valuable enough, but keeping it for now.

**Comment by MichalBryxi** [comment]
Heh, this _hack_ would solve it for me:

```js
// work with your AST as normal
let template = `<img src="foo {{bar}} baz">`;
let original = parse(template);
let element = original.body[0] as AST.ElementNode;
let attribute = element.attributes[0] as AST.AttrNode;
let concat = attribute.value as AST.ConcatStatement;

// before trying to print it, parse an empty document
let reconstructed = parse('') as any;
// attach your AST parts to that document
reconstructed.body = [builders.concat([concat.parts[0], concat.parts[1]])];

// now print works
expect(print(reconstructed)).toEqual(`<img src="foo {{bar}}">`);
```

**Comment by dcyriller** [comment]
FYI I pushed two commits to change a bit the tests. I also pushed a third commit to fix the bug. @rwjblue I don't remember why there is an ovveride. If you mind having a look, I am not entirely sure of the fix.

**Comment by courajs** [comment]
Heya! This fix stops the infinite loop, but won't reproduce the formatting of any parsed nodes that are nested inside. I have a fix that plays better with formatting here: https://github.com/ember-template-lint/ember-template-recast/pull/671

**Comment by dcyriller** [comment]
Hey @courajs, #671 sounds like a nice improvement.

I am closing this PR in favor of #671 as it allows preserving the formatting when reusing nodes from a previously parsed template.

Thanks a lot @MichalBryxi for the report!

**Pull request closed without merging**
