### PR TITLE
Add failing autofix test (prettier style)

### PR DESCRIPTION
**Pull request by dcyriller**
https://github.com/ember-template-lint/ember-template-recast/pull/254 added a prettier style autofix test.

This PR highlights a failing scenario 😭. As you can see, the replacement generated by Prettier inserts newlines inside an ElementNode's attributes. Since these newlines are not present in the AST, I'm unsure how to print them. Any idea is welcome 😄.

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm, can you also add a failing test in the parse-result-test section for ElementNode that starts with:

```hbs
<div data-foo
 data-bar="lol"
      some-other-thing={{haha}}>
</div>
```

And add a new attribute, preserving the pre-existing whitespace. I _think_ you are basically reporting that this would **not** work...

**Comment by dcyriller** [comment]
It will be fixed to: 
```html
<div data-foo data-bar="lol" some-other-thing={{haha}}>
</div>
```

>  I think you are basically reporting that this would not work

Yeah, this is the vague idea I was having (and a bit afraid of).

**Comment by dcyriller** [comment]
@rwjblue, _for what it's worth_: I still believe that your idea - using recast to fix templates - was a good idea. Because we mostly want to fix syntastic issues (more than stylistic / formatting issues). And using recast seems more "efficient" than a string-based approach to do that.

To apply stylistic / formatting fixes, what do you think of creating a new method in template-lint public API? Along with `verify` and `verifyAndFix`, we could have a `verifyFixAndFormat` or `verifyFixAndStyle` method? It would verify and fix templates and then apply formatting.

We'd probably have to log these new warnings / errors as `isFormatable: true` to be able to apply formatting _after_ the fixes.

(I'm not saying I'll have enough time to implement that tomorrow or next week 😄).

**Comment by rwjblue** [comment]
Well, we really do need to fix the issue of whitespace formatting being lost for adding a new attribute (like I mentioned in my prior comment). I'm not clear if that is the only issue making this not work though, or if that is just the tip of the iceburg...

**Comment by dcyriller** [comment]
okay @rwjblue I think I missed an essential feature of recast 😄

**Comment by dcyriller** [comment]
I now get what the problem is. It is not that we're printing attributes. But that we're switching `node.body` to `recast(replacement).body`. `recast(replacement).body` itself has not been parsed by recast, only `replacement`. So, when printing `recast(replacement).body`, recast instance doesn't have an existing representation of the ast.

**Comment by dcyriller** [comment]
@rwjblue may you have a look to this (🤞 I hope not too much hacky) fix?

**Comment by rwjblue** [comment]
Hm, I don’t think it would always be body though, right?

**Comment by dcyriller** [comment]
It would only fix the case where we want to switch `body`. If we want to replace some other node, we'd have a similar issue indeed.

**Comment by dcyriller** [comment]
I'm running out of idea here @rwjblue.

If you had a pointer or an idea I could explore, it would be awesome!

**Comment by dcyriller** [comment]
Sorry for the noise @rwjblue 🤦.

I was missing a recast feature (it keeps whitespaces around `AttrNode`s, even when they are modified). And I didn't understand what you were suggesting in your first comment because I was too focused on the way I was seeing the problem. Now reading your comment again, it makes total sense.

So, I'm going to open a PR focused on the test you suggested to write in a first place.

And I'm going to open a second PR to (hopefully) better explain the problem I'm facing.

**Pull request closed without merging**
